// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	domain "github.com/odpf/guardian/domain"
	mock "github.com/stretchr/testify/mock"
)

// ResourceService is an autogenerated mock type for the resourceService type
type ResourceService struct {
	mock.Mock
}

// Find provides a mock function with given fields: _a0
func (_m *ResourceService) Find(_a0 map[string]interface{}) ([]*domain.Resource, error) {
	ret := _m.Called(_a0)

	var r0 []*domain.Resource
	if rf, ok := ret.Get(0).(func(map[string]interface{}) []*domain.Resource); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Resource)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(map[string]interface{}) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: _a0
func (_m *ResourceService) Get(_a0 *domain.ResourceIdentifier) (*domain.Resource, error) {
	ret := _m.Called(_a0)

	var r0 *domain.Resource
	if rf, ok := ret.Get(0).(func(*domain.ResourceIdentifier) *domain.Resource); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Resource)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*domain.ResourceIdentifier) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
