project_name: guardian

release:
  draft: true
  prerelease: auto

before:
  hooks:
    - go mod tidy
    - make clean

builds:
  - main: ./main.go
    id: "guardian"
    binary: guardian
    flags:
      - -a
    ldflags:
      - -s -w -X github.com/odpf/guardian/main.Version={{.Tag}} -X github.com/odpf/guardian/main.BuildCommit={{.FullCommit}} -X github.com/odpf/guardian/main.BuildDate={{.Date}}
    goos: [darwin, linux, windows]
    goarch: [amd64, 386, arm, arm64]
    env:
      - CGO_ENABLED=0

archives:
  - replacements:
      darwin: macos
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^build:"

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

dockers:
  - goos: linux
    goarch: amd64
    ids:
      - guardian
    dockerfile: Dockerfile
    image_templates:
      - "docker.io/odpf/{{.ProjectName}}:latest"
      - "docker.io/odpf/{{.ProjectName}}:{{ .Version }}"
      - "docker.io/odpf/{{.ProjectName}}:{{ .Tag }}-amd64"

brews:
  - name: guardian
    homepage: "https://github.com/odpf/guardian"
    description: "Metadata collection tool."
    tap:
      owner: odpf
      name: homebrew-taps
    license: "Apache 2.0"
    folder: Formula
    dependencies:
      - name: git
    install: |-
      bin.install "guardian"
    commit_author:
      name: Ravi Suhag
      email: ravi.suhag@gmail.com
