DROP INDEX IF EXISTS idx_appeals_created_by_status_deleted_at_updated_at;
DROP INDEX IF EXISTS idx_appeals_id_deleted_at_null;
DROP INDEX IF EXISTS idx_approvers_approval_id_deleted_at_null;
DROP INDEX IF EXISTS idx_grants_appeal_id_deleted_at_null;
DROP INDEX IF EXISTS idx_grants_status_deleted_at_null;
DROP INDEX IF EXISTS idx_resources_id_deleted_at_null;