// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	iam "cloud.google.com/go/iam"
	gcs "github.com/odpf/guardian/plugins/providers/gcs"

	mock "github.com/stretchr/testify/mock"
)

// GcsClient is an autogenerated mock type for the GcsClient type
type GcsClient struct {
	mock.Mock
}

type GcsClient_Expecter struct {
	mock *mock.Mock
}

func (_m *GcsClient) EXPECT() *GcsClient_Expecter {
	return &GcsClient_Expecter{mock: &_m.Mock}
}

// GetBuckets provides a mock function with given fields: ctx, projectID
func (_m *GcsClient) GetBuckets(ctx context.Context, projectID string) ([]*gcs.Bucket, error) {
	ret := _m.Called(ctx, projectID)

	var r0 []*gcs.Bucket
	if rf, ok := ret.Get(0).(func(context.Context, string) []*gcs.Bucket); ok {
		r0 = rf(ctx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*gcs.Bucket)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GcsClient_GetBuckets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBuckets'
type GcsClient_GetBuckets_Call struct {
	*mock.Call
}

// GetBuckets is a helper method to define mock.On call
//  - ctx context.Context
//  - projectID string
func (_e *GcsClient_Expecter) GetBuckets(ctx interface{}, projectID interface{}) *GcsClient_GetBuckets_Call {
	return &GcsClient_GetBuckets_Call{Call: _e.mock.On("GetBuckets", ctx, projectID)}
}

func (_c *GcsClient_GetBuckets_Call) Run(run func(ctx context.Context, projectID string)) *GcsClient_GetBuckets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *GcsClient_GetBuckets_Call) Return(_a0 []*gcs.Bucket, _a1 error) *GcsClient_GetBuckets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GrantBucketAccess provides a mock function with given fields: ctx, b, identity, role
func (_m *GcsClient) GrantBucketAccess(ctx context.Context, b *gcs.Bucket, identity string, role iam.RoleName) error {
	ret := _m.Called(ctx, b, identity, role)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gcs.Bucket, string, iam.RoleName) error); ok {
		r0 = rf(ctx, b, identity, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GcsClient_GrantBucketAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GrantBucketAccess'
type GcsClient_GrantBucketAccess_Call struct {
	*mock.Call
}

// GrantBucketAccess is a helper method to define mock.On call
//  - ctx context.Context
//  - b *gcs.Bucket
//  - identity string
//  - role iam.RoleName
func (_e *GcsClient_Expecter) GrantBucketAccess(ctx interface{}, b interface{}, identity interface{}, role interface{}) *GcsClient_GrantBucketAccess_Call {
	return &GcsClient_GrantBucketAccess_Call{Call: _e.mock.On("GrantBucketAccess", ctx, b, identity, role)}
}

func (_c *GcsClient_GrantBucketAccess_Call) Run(run func(ctx context.Context, b *gcs.Bucket, identity string, role iam.RoleName)) *GcsClient_GrantBucketAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*gcs.Bucket), args[2].(string), args[3].(iam.RoleName))
	})
	return _c
}

func (_c *GcsClient_GrantBucketAccess_Call) Return(_a0 error) *GcsClient_GrantBucketAccess_Call {
	_c.Call.Return(_a0)
	return _c
}

// RevokeBucketAccess provides a mock function with given fields: ctx, b, identity, role
func (_m *GcsClient) RevokeBucketAccess(ctx context.Context, b *gcs.Bucket, identity string, role iam.RoleName) error {
	ret := _m.Called(ctx, b, identity, role)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gcs.Bucket, string, iam.RoleName) error); ok {
		r0 = rf(ctx, b, identity, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GcsClient_RevokeBucketAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeBucketAccess'
type GcsClient_RevokeBucketAccess_Call struct {
	*mock.Call
}

// RevokeBucketAccess is a helper method to define mock.On call
//  - ctx context.Context
//  - b *gcs.Bucket
//  - identity string
//  - role iam.RoleName
func (_e *GcsClient_Expecter) RevokeBucketAccess(ctx interface{}, b interface{}, identity interface{}, role interface{}) *GcsClient_RevokeBucketAccess_Call {
	return &GcsClient_RevokeBucketAccess_Call{Call: _e.mock.On("RevokeBucketAccess", ctx, b, identity, role)}
}

func (_c *GcsClient_RevokeBucketAccess_Call) Run(run func(ctx context.Context, b *gcs.Bucket, identity string, role iam.RoleName)) *GcsClient_RevokeBucketAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*gcs.Bucket), args[2].(string), args[3].(iam.RoleName))
	})
	return _c
}

func (_c *GcsClient_RevokeBucketAccess_Call) Return(_a0 error) *GcsClient_RevokeBucketAccess_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewGcsClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewGcsClient creates a new instance of GcsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGcsClient(t mockConstructorTestingTNewGcsClient) *GcsClient {
	mock := &GcsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
