// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IdentityManagerService is an autogenerated mock type for the IdentityManagerService type
type IdentityManagerService struct {
	mock.Mock
}

// GetUserApproverEmails provides a mock function with given fields: userEmail
func (_m *IdentityManagerService) GetUserApproverEmails(userEmail string) ([]string, error) {
	ret := _m.Called(userEmail)

	var r0 []string
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(userEmail)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userEmail)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
