// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	idtoken "google.golang.org/api/idtoken"
)

// OidcValidator is an autogenerated mock type for the Validator type
type OidcValidator struct {
	mock.Mock
}

// Validate provides a mock function with given fields: ctx, token, audience
func (_m *OidcValidator) Validate(ctx context.Context, token string, audience string) (*idtoken.Payload, error) {
	ret := _m.Called(ctx, token, audience)

	var r0 *idtoken.Payload
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *idtoken.Payload); ok {
		r0 = rf(ctx, token, audience)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*idtoken.Payload)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, token, audience)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewOidcValidator interface {
	mock.TestingT
	Cleanup(func())
}

// NewOidcValidator creates a new instance of OidcValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewOidcValidator(t mockConstructorTestingTNewOidcValidator) *OidcValidator {
	mock := &OidcValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
