// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/odpf/guardian/domain"
	mock "github.com/stretchr/testify/mock"
)

// ProviderUsecase is an autogenerated mock type for the ProviderUsecase type
type ProviderUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0
func (_m *ProviderUsecase) Create(_a0 domain.Provider) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.Provider) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
