name: Main
on:
  push:
    branches:
      - main

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish dev image
        id: docker_dev_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: "./Dockerfile.dev"
          tags: raystack/guardian:dev
